### ISSUE TITLE
User Story 4 - Manter Recurso

### ISSUE THREAD

**Issue by tgo-mas** [tgo-mas/SIGApoio#23]
Manter Recurso é o antigo Manter Item. Onde for item trocar para recurso. Adicionar na descrição os tipos de recurso (adaptador hdmi, projetor, notebook e caixa de som) e a tela de reservas de recursos.
Analista: a pessoa que detalhou o user story
as demais funções serão decididas na daily.
Requisitos: RF16, RF17, RF18, RF19, RF20, RF21, RF22
Os testes de aceitação devem conter: cadastro do recurso, cadastro com erro, edição do recurso, exclusão do recurso, pesquisa por recurso, registro de entrada/saída com sucesso e com erro.

**Comment by AndersonAzeved** [comment]
# Algumas dúvidas pra daily: 
* Quais atributos o recurso tem?  Tem categoria?
* Definir o quadro de prioridades 
* Conferir os Testes de aceitação
